css-ecommerce-page
alexjraymond/c1222-code-solutions pull request #31
Opened 2022-12-14 19:01 UTC by alexjraymond

<img width="1305" alt="image" src="https://user-images.githubusercontent.com/117477893/207688421-231ac641-5a84-4b67-86eb-99e591c98f08.png">

2022-12-14 19:04 UTC, alexjraymond commented
so the LV bag originally was ~40px above the rest of the images/etc, idk if impacting aspect ratio and adding padding-top was the right move with the .lv in my css, but yeah

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/117477893/207689198-cdb3ca21-0196-4bca-b66e-5965c873f556.png">

2022-12-16 23:27 UTC, codingcodymiller requested changes

2022-12-16 23:27 UTC, codingcodymiller commented on css-ecommerce-page/styles.css
> +  height: auto;
I would just give this a set height, and use `object-fit` on the images to adjust how they render in the available space.

2022-12-20 19:49 UTC, alexjraymond reviewed
![image](https://user-images.githubusercontent.com/117477893/208754059-b596d606-1ec2-4ce7-9007-3e07eb01cd7d.png)

2022-12-20 19:49 UTC, merged