Array manipulation 2
alexjraymond/c1222-code-solutions pull request #64
Opened 2023-01-18 19:53 UTC by alexjraymond

<img width="471" alt="CleanShot 2023-01-18 at 11 52 54@2x" src="https://user-images.githubusercontent.com/117477893/213280877-fadb189b-6e18-4cec-a139-5f9bcf103ac9.png">

2023-01-19 18:00 UTC, codingcodymiller requested changes

2023-01-20 00:35 UTC, alexjraymond commented on array-manipulation-2/src/chunk.js
> +}
i think i had a derp in the brain, new update is this  should work
![CleanShot 2023-01-19 at 16 33 05](https://user-images.githubusercontent.com/117477893/213592747-10d771e4-a78f-41bf-8fbe-605a79905abd.png)

2023-01-20 00:35 UTC, alexjraymond commented on array-manipulation-2/src/chunk.js
> +}
minus console log of course........

2023-01-20 21:43 UTC, codingcodymiller approved these changes

2023-01-23 18:19 UTC, merged