express-post-json
alexjraymond/c1222-code-solutions pull request #89
Opened 2023-01-27 22:21 UTC by alexjraymond

![CleanShot 2023-01-27 at 13 55 59](https://user-images.githubusercontent.com/117477893/215216724-c8142fff-0912-4fbb-9482-5c27fcccf281.png)

2023-01-27 23:03 UTC, RobertGardner requested changes

2023-01-27 23:04 UTC, alexjraymond commented on express-post-json/index.js
> +// const fsPromises = require('fs').promises;
i was so excited, like a kid on christmas

2023-01-27 23:36 UTC, RobertGardner requested changes

2023-01-27 23:36 UTC, RobertGardner commented on express-post-json/index.js
>    res.sendStatus(201);
Almost. You're still just returning the status. You should also return the new grade object.

2023-01-30 21:32 UTC, RobertGardner approved these changes

2023-01-30 21:32 UTC, merged